from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

from row_taker.engine.game.state import PublicState
from row_taker.gui_workbench.scenario_types import DEFAULT_SIZE, GameWorkbenchScenario


@dataclass(frozen=True, slots=True)
class WorkbenchTimeline:
    """A deterministic sequence of production GUI states.

    The states are generated by the real hub, client core, reducer and
    ``GameFrame`` input path. Navigation later only selects among these frozen
    states; it does not recreate game or presentation logic in the workbench.
    """

    name: str
    description: str
    steps: tuple[GameWorkbenchScenario, ...]
    expected_final_public_state: PublicState
    default_size: tuple[int, int] = DEFAULT_SIZE

    def __post_init__(self) -> None:
        if not self.steps:
            raise ValueError("a workbench timeline requires at least one step")

TimelineFactory = Callable[[], WorkbenchTimeline]


def _timeline_factories() -> dict[str, TimelineFactory]:
    from row_taker.gui_workbench.timeline_builders import build_full_trick_timeline

    return {"full-trick": build_full_trick_timeline}


def timeline_names() -> tuple[str, ...]:
    return tuple(_timeline_factories())


def get_timeline(name: str) -> WorkbenchTimeline:
    factories = _timeline_factories()
    try:
        factory = factories[name]
    except KeyError as exc:
        available = ", ".join(factories)
        raise KeyError(f"unknown workbench timeline {name!r}; available: {available}") from exc
    return factory()


def timelines() -> tuple[WorkbenchTimeline, ...]:
    return tuple(factory() for factory in _timeline_factories().values())
