from __future__ import annotations

WINDOW_TITLE = "Row-Taker"
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 700
FPS = 60

BACKGROUND_COLOR = (0, 120, 0)

CARD_GAP = 10
CARD_SCALE = 0.1
CARD_ASPECT_RATIO = 1.5
HANDCARD_SCALE = CARD_SCALE / 1.4
HANDCARD_GAP = CARD_GAP * 3.5
OFFSET_HANDCARD_X = 23

BOARD_PLAY_AREA_X_RATIO = 0.015
BOARD_PLAY_AREA_Y_RATIO = 0.07
BOARD_PLAY_AREA_WIDTH_RATIO = 0.8
BOARD_PLAY_AREA_HEIGHT_RATIO = 0.85
